#########################
#     HealthPerKill     #
#########################

#How much half hearts to add when you kill some one
set_health: 4.0

#The sound list can be found ---> https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
set_sound: ENTITY_IRON_GOLEM_DEATH