#########################
#     HealthPerKill     #
#########################

#How much half hearts to add when you kill some one
set_health: 4.0

#The sound list can be found ---> https://goo.gl/tpxSTU
set_sound: ENTITY_IRONGOLEM_DEATH