#########################
#     HealthPerKill     #
#########################

#How much hearts to add when you kill some one
set_health: 2.0

#The sound list can be found ---> http://goo.gl/0T9Iac
set_sound: IRONGOLEM_DEATH